# Generated by Django 5.0.6 on 2024-06-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='depatment',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.FloatField(),
        ),
    ]
